# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('published_date', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feed_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.CharField(max_length=300)),
                ('feed_source', models.CharField(max_length=100)),
                ('last_updated', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
