# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlenews', '0002_feed_details_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_details',
            name='last_updated',
            field=models.CharField(default=datetime.datetime(2019, 10, 10, 16, 10, 19, 547000), max_length=150),
        ),
    ]
