# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlenews', '0004_auto_20191010_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_details',
            name='last_updated',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
